language: ruby
gemfile:
  - gemfiles/rails23.gemfile
  #- gemfiles/rails30.gemfile
  #- gemfiles/rails31.gemfile
  #- gemfiles/rails32.gemfile
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
jdk:
  - oraclejdk7
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails23.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails23.gemfile
    - rvm: jruby-19mode
      gemfile: gemfiles/rails23.gemfile
    - rvm: jruby-head
      gemfile: gemfiles/rails23.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/rails23.gemfile
  allow_failures:
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-19mode
    - rvm: ruby-head
